services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: production
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env
    networks:
      - compareai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
      args:
        - VITE_API_URL=/api
    volumes:
      - ./frontend/dist:/app/dist
    depends_on:
      - backend
    networks:
      - compareai-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - compareai-network

networks:
  compareai-network:
    driver: bridge
